name: CI - Build, Test & Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      OWM_URL: ${{ secrets.OWM_URL }}
      OWM_KEY: ${{ secrets.OWM_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. Build with Maven
      - name: Build JAR
        run: ./mvnw clean install -DskipTests

      # 4. Run tests
      - name: Run tests
        run: ./mvnw test

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t weathermate-backend .
